insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Tao of Steve, The', 15, '25-Mar-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Parasite', 19, '06-Dec-2021', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Over the Top', 19, '13-Nov-2021', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('High and Dizzy', 19, '27-Dec-2021', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Girl by the Lake, The (La ragazza del lago)', 15, '07-Nov-2022', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Thank You for Smoking', 15, '26-Jan-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Commandos Strike at Dawn', 19, '24-Oct-2022', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Comrade X', 0, '26-Aug-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Robot Stories', 0, '25-May-2022', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Very British Gangster, A', 0, '03-Apr-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('A Patriotic Man', 19, '23-Feb-2022', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Toothless', 0, '08-Jan-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Adventures of Arsène Lupin, The (Aventures d''Arsène Lupin, Les)', 15, '03-Oct-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Journey, The', 19, '03-Apr-2022', 95);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Hangman''s Knot', 19, '21-Oct-2022', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Home Room', 15, '27-Jun-2022', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Densha otoko (Train Man)', 0, '17-Jul-2022', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('City Hunter (Sing si lip yan)', 15, '21-May-2022', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Man, Woman and Beast (L''uomo la donna e la bestia)', 19, '11-Aug-2022', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Glengarry Glen Ross', 19, '05-Jun-2022', 180);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Delicacy (La délicatesse)', 15, '15-Aug-2022', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Road House', 19, '29-Sep-2022', 210);
insert into movie_data (movie_title, movie_age_restriction, movie_release_date, movie_time) values ('Arrangement, The', 0, '29-Dec-2021', 95);
