/*user table settings*/
--DROP TABLE user_data PURGE;
CREATE TABLE user_data(
    user_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    age_restriction CHAR(1) CONSTRAINT user_data_age_restriction_ck
        CHECK(age_restriction = '0' OR age_restriction = '1'),
    marketing_agreement CHAR(1) CONSTRAINT user_data_marketing_agreement_ck
        CHECK(marketing_agreement = '0' OR marketing_agreement = '1'),
    logtime DATE DEFAULT sysdate,
    CONSTRAINT user_data_unique UNIQUE (email)
);
--make user_id identity restart
--ALTER TABLE user_data MODIFY(user_id GENERATED AS IDENTITY (START WITH 1));

--DROP TABLE user_membership
CREATE TABLE user_membership(
    user_id INT,
    user_membership_type VARCHAR(50),
    user_membership_start_date VARCHAR(50)
);



/*movie table settings*/
--DROP TABLE movie_data
CREATE TABLE movie_data(
    movie_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    movie_title VARCHAR(50),
    movie_age_restriction SMALLINT,
    movie_release_date DATE,
    movie_time SMALLINT
);
--make movie_id identity restart
--ALTER TABLE movie_data MODIFY(movie_id GENERATED AS IDENTITY (START WITH 1));

--DROP TABLE movie_rating
CREATE TABLE movie_rating(
    movie_id INT,
    review_id INT,
    rating_start SMALLINT,
    num_of_ratings SMALLINT
);

--DROP TABLE movie_reviewer
CREATE TABLE movie_reviewer(
    review_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    review_description VARCHAR(255),
    user_id INT --name join
);
--make review_id identity restart
--ALTER TABLE movie_reviewer MODIFY(review_id GENERATED AS IDENTITY (START WITH 1));

--DROP TABLE movie_cast
CREATE TABLE movie_cast(
    movie_id INT,
    actor_id INT
);

--DROP TABLE movie_genre
CREATE TABLE movie_genre(
    movie_id INT,
    genre_id INT
);

--DROP TABLE actor
CREATE TABLE actor(
    actor_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    actor_fname VARCHAR(50),
    actor_lname VARCHAR(50)
);
--make actor_id identity restart
--ALTER TABLE actor MODIFY(actor_id GENERATED AS IDENTITY (START WITH 1));

--DROP TABLE genre
CREATE TABLE genre(
    genre_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    genre_title VARCHAR(50)
);
--make genre_id identity restart
--ALTER TABLE genre MODIFY(genre_id GENERATED AS IDENTITY (START WITH 1));



/*search page settings*/
DROP TABLE search_title PURGE;
CREATE TABLE search_title(
    video_genre VARCHAR2(50),
    webtoon_genre VARCHAR2(50),
    video_nation VARCHAR2(50)
);
INSERT INTO search_title VALUES('판타지','판타지','한국');
INSERT INTO search_title VALUES('코미디','코미디','중국');
INSERT INTO search_title VALUES('한국 드라마','미스터리','미국');
INSERT INTO search_title VALUES('미국 드라마','공포','이탈리아');
INSERT INTO search_title VALUES('로맨스','로맨스','인도');
INSERT INTO search_title VALUES('액션','액선','필리핀');
INSERT INTO search_title VALUES('애니메이션','','');
INSERT INTO search_title VALUES('음악','','');
INSERT INTO search_title VALUES('블록버스터','','');
INSERT INTO search_title VALUES('공포','','');

commit;